baseURL = "/"
languageCode = "en-us"
theme = "hugo-serif-theme"
themesDir = "themes"
title = "Hugo Serif Theme"
[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 3
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Team"
url = "/team/"
weight = 4
[[menu.main]]
name = "Services"
url = "/services/"
weight = 3
[params]
google_analytics_id = ""
[params.homepage_meta_tags]
meta_description = "We are creating a new type of agency"
meta_og_description = "Marketing agency"
meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
meta_og_title = "A new agency"
meta_og_type = "website"
meta_og_url = "https://hugo-serif.netlify.com"
meta_twitter_card = "summary"
meta_twitter_creator = "@pastelpad"
meta_twitter_site = "@pastelpad"
[params.logo]
alt = "Serif - A Hugo Business Theme"
mobile = "/images/logo-mobile.svg"
standard = "/images/logo.svg"
